name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build
      run: |
        python build.py
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/serenify.exe
        tag_name: v0.0.1